#programa média 
nome = input(" informe o nome do estudante : " )
n1 = float(input("informe a nota 1: "))
n2 = float(input("informe a nota 2:"))
media = (n1+n2)/2
print(f"Sr (a) {nome} , sua média é {media}")
# programa peso ideal 
altura  = float ("informe a sua altura :(metros): " ))
homens = (72.7 * altura ) - 58
mulheres=  (62.1 * altura) - 44. 7
print(f"Opeso ideal  para os homens é {homens} é kg, 
enquanto para mulheres é {mulheres:.2f} kg.")     




#peso iedal 
altura = input(" informe sua altura ")
n2 = float(input("informe seu peso ;")) 
result = (n1+n2)-58
print ("o peso ideal è ; result")